# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 706017823a617b97bea9a53f548c8e0b037d11f5067cf96238c4b0e0283a683d938b4ec3f126b13d24137f6f10db05b910331355b6d710a90bed0bd39b9a468b

test:
  secret_key_base: 393ca737e442a76a156fd4098e34f661bcae02684bc226d24ee2850228c41aac76abef510c4802621c973d37b1d00587093ca822804e7c1d883cc1b17f833cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
